version: '3'

services:
  django:
    build:
      context: .
    image: account:v1.0.1
    restart: "always"
    ports:
      - '8888:8888'
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 300m
    working_dir: /home/workspace
      - ./logs:/home/workspace/logs
    command: ["jupyter", "notebook"]
      test: curl --fail http://localhost:8888||exit 1
      interval: 50s
      timeout: 5s
      retries: 6